# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Code Snippet', max_length=30)),
                ('code', models.TextField()),
                ('updateTime', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeshare.Course'),
        ),
    ]
