# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
