# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0002_remove_course_isprivate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='creator',
        ),
        migrations.AddField(
            model_name='course',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
