# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 15:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0002_auto_20161027_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='updateTime',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 27, 11, 24, 2)),
        ),
    ]
