# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0003_auto_20161027_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(default='Code Snippet', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='updateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
