# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0004_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='isPrivate',
            field=models.NullBooleanField(default=False),
        ),
    ]
