# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0004_auto_20161027_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='updateTime',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
