# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0005_auto_20161029_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='updated',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
