# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0005_auto_20161220_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
