# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codeshare', '0009_course_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeshare.Instructor'),
        ),
    ]
